# Generated by Django 5.1.6 on 2025-04-22 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tiêu đề")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tuyen_sinh", "Tuyển sinh"),
                            ("huong_nghiep", "Hướng nghiệp"),
                            ("hoc_bong", "Học bổng"),
                        ],
                        max_length=20,
                        verbose_name="Danh mục",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="news/images/", verbose_name="Hình ảnh"
                    ),
                ),
                ("content", models.TextField(verbose_name="Nội dung")),
                ("excerpt", models.TextField(max_length=300, verbose_name="Tóm tắt")),
                (
                    "author",
                    models.CharField(
                        default="Admin", max_length=100, verbose_name="Tác giả"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="Lượt xem"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Hiển thị"),
                ),
            ],
            options={
                "verbose_name": "Tin tức",
                "verbose_name_plural": "Tin tức",
                "ordering": ["-created_at"],
            },
        ),
    ]
