# Generated by Django 5.1.6 on 2025-04-22 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="category",
        ),
        migrations.RemoveField(
            model_name="news",
            name="view_count",
        ),
    ]
