# Generated by Django 5.1.6 on 2025-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_remove_news_category_remove_news_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                upload_to="static/assets/img/news/", verbose_name="Hình ảnh"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Hiển thị"),
        ),
    ]
