# Generated by Django 5.1.6 on 2025-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_image_alter_news_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="excerpt",
            field=models.TextField(max_length=300, null=True, verbose_name="Tóm tắt"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ImageField(
                null=True, upload_to="static/assets/img/news/", verbose_name="Hình ảnh"
            ),
        ),
    ]
