# Generated by Django 5.1.6 on 2025-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_alter_news_excerpt_alter_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="excerpt",
        ),
    ]
