# Generated by Django 5.1.6 on 2025-09-18 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0002_alter_workschedule_expert"),
        ("homepage", "0007_rename_expert_description_expert_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workschedule",
            name="expert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule",
                to="homepage.expert",
            ),
        ),
    ]
