# Generated by Django 5.1.6 on 2025-09-19 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0003_alter_workschedule_expert"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workshift",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="workschedule",
            name="work_shift",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift",
                to="advise.workshift",
            ),
            preserve_default=False,
        ),
    ]
