# Generated by Django 5.1.6 on 2025-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0004_remove_workshift_work_schedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workschedule",
            name="is_approved",
            field=models.CharField(
                choices=[
                    ("Y", "Đã được duyệt"),
                    ("P", "Đang chờ duyệt"),
                    ("C", "Đã hủy"),
                ],
                default="Đang chờ duyệt",
                max_length=20,
            ),
        ),
    ]
