# Generated by Django 5.1.6 on 2025-10-01 06:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0005_workschedule_is_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workschedule",
            old_name="is_approved",
            new_name="status",
        ),
    ]
