# Generated by Django 5.1.6 on 2025-10-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0006_rename_is_approved_workschedule_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workschedule",
            name="status",
            field=models.CharField(
                choices=[
                    ("Y", "Đã được duyệt"),
                    ("P", "Đang chờ duyệt"),
                    ("C", "Đã hủy"),
                ],
                default="P",
                max_length=20,
            ),
        ),
    ]
