# Generated by Django 5.1.6 on 2025-10-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0008_appointment"),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=3, default=200.0, max_digits=7),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("N", "Chưa thanh toán"), ("Y", "Đã thanh toán")],
                        max_length=20,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.member",
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="advise.workschedule",
                    ),
                ),
            ],
        ),
    ]
