# Generated by Django 5.1.6 on 2025-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0009_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Y", "Đã xong"),
                    ("P", "Đang thực hiện"),
                    ("N", "Chưa thực hiện"),
                ],
                default="N",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[("N", "Chưa thanh toán"), ("Y", "Đã thanh toán")],
                default="N",
                max_length=20,
            ),
        ),
    ]
