# Generated by Django 5.1.6 on 2025-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0010_alter_appointment_status_alter_invoice_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_id",
            field=models.CharField(default="HD202510061710", max_length=15),
        ),
    ]
