# Generated by Django 5.1.6 on 2025-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0011_invoice_invoice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_id",
            field=models.CharField(max_length=15),
        ),
    ]
