# Generated by Django 5.1.6 on 2025-10-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0012_alter_invoice_invoice_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="member",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="work_schedule",
        ),
        migrations.AddField(
            model_name="invoice",
            name="appointment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="advise.appointment",
            ),
            preserve_default=False,
        ),
    ]
