# Generated by Django 5.1.6 on 2025-10-07 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0013_remove_invoice_member_remove_invoice_work_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zoom_id", models.CharField(max_length=10, unique=True)),
                ("password", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="zoom_room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="advise.room"
            ),
            preserve_default=False,
        ),
    ]
