# Generated by Django 5.1.6 on 2025-10-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0014_room_appointment_zoom_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="zoom_room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="advise.room"
            ),
        ),
    ]
