# Generated by Django 5.2.7 on 2025-12-02 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advise', '0015_alter_appointment_zoom_room'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='chat_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='chat.chatgroup'),
            preserve_default=False,
        ),
    ]
