# Generated by Django 5.2.7 on 2025-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advise', '0016_appointment_chat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Y', 'Đã xong'), ('P', 'Đang thực hiện'), ('N', 'Chưa thực hiện'), ('C', 'Đã hủy')], default='N', max_length=20),
        ),
    ]
