# Generated by Django 5.1.6 on 2025-11-03 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0016_appointment_chat_group"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="chat_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.chatgroup"
            ),
        ),
    ]
