# Generated by Django 5.1.6 on 2025-11-03 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0017_alter_appointment_chat_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="chat_group",
        ),
    ]
