# Generated by Django 5.1.6 on 2025-11-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advise", "0018_remove_appointment_chat_group"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="chat_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chatgroup",
            ),
        ),
    ]
