# Generated by Django 5.1.6 on 2025-10-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('num_questions', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='BlockTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('suggested_majors', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testblock.testblock')),
            ],
        ),
        migrations.CreateModel(
            name='BlockQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('test_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testblock.testblock')),
            ],
        ),
    ]
