# Generated by Django 5.1.6 on 2025-10-07 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblock', '0002_alter_blocktestresult_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A_TOAN', 'Toán Khối A'), ('A_LY', 'Vật Lý Khối A'), ('A_HOA', 'Hóa Học Khối A'), ('B_TOAN', 'Toán Khối B'), ('B_HOA', 'Hóa Học Khối B'), ('B_SINH', 'Sinh Học Khối B'), ('C_VAN', 'Ngữ Văn Khối C'), ('C_SU', 'Lịch Sử Khối C'), ('C_DIA', 'Địa Lý Khối C'), ('D_TOAN', 'Toán Khối D'), ('D_VAN', 'Ngữ Văn Khối D'), ('D_TA', 'Tiếng Anh Khối D'), ('A01_TOAN', 'Toán Khối A01'), ('A01_LY', 'Vật Lý Khối A01'), ('A01_TA', 'Tiếng Anh Khối A01'), ('B01_TOAN', 'Toán Khối B01'), ('B01_SINH', 'Sinh Học Khối B01'), ('B01_TA', 'Tiếng Anh Khối B01'), ('D01_TOAN', 'Toán Khối D01'), ('D01_VAN', 'Ngữ Văn Khối D01'), ('D01_TA', 'Tiếng Anh Khối D01'), ('D07_TOAN', 'Toán Khối D07'), ('D07_HOA', 'Hóa Học Khối D07'), ('D07_TA', 'Tiếng Anh Khối D07')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time_limit', models.IntegerField(default=90)),
                ('total_questions', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_questions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_taken', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testblock.subject')),
            ],
        ),
    ]
