# Generated by Django 5.1.6 on 2025-10-08 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblock', '0003_subject_subjecttestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockquestion',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testblock.subject'),
            preserve_default=False,
        ),
    ]
