# Generated by Django 5.1.6 on 2025-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblock', '0004_blockquestion_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttestresult',
            name='question_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(choices=[('A_TOAN', 'Toán Khối A'), ('A_LY', 'Vật Lý Khối A'), ('A_HOA', 'Hóa Học Khối A'), ('B_TOAN', 'Toán Khối B'), ('B_HOA', 'Hóa Học Khối B'), ('B_SINH', 'Sinh Học Khối B'), ('C_VAN', 'Ngữ Văn Khối C'), ('C_SU', 'Lịch Sử Khối C'), ('C_DIA', 'Địa Lý Khối C'), ('D_TOAN', 'Toán Khối D'), ('D_VAN', 'Ngữ Văn Khối D'), ('D_TA', 'Tiếng Anh Khối D'), ('A01_TOAN', 'Toán Khối A01'), ('A01_LY', 'Vật Lý Khối A01'), ('A01_TA', 'Tiếng Anh Khối A01')], max_length=10, unique=True),
        ),
    ]
