# Generated by Django 5.1.6 on 2025-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblock', '0005_subjecttestresult_question_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(choices=[('A_TOAN', 'Toán Khối A'), ('A_LY', 'Vật Lý Khối A'), ('A_HOA', 'Hóa Học Khối A'), ('B_TOAN', 'Toán Khối B'), ('B_HOA', 'Hóa Học Khối B'), ('B_SINH', 'Sinh Học Khối B'), ('C_VAN', 'Ngữ Văn Khối C'), ('C_SU', 'Lịch Sử Khối C'), ('C_DIA', 'Địa Lý Khối C'), ('D_TOAN', 'Toán Khối D'), ('D_VAN', 'Ngữ Văn Khối D'), ('D_TA', 'Tiếng Anh Khối D'), ('A01_TOAN', 'Toán Khối A01'), ('A01_LY', 'Vật Lý Khối A01'), ('A01_TA', 'Tiếng Anh Khối A01'), ('B01_TOAN', 'Toán Khối B01'), ('B01_HOA', 'Hóa Học Khối B01'), ('B01_TA', 'Tiếng Anh Khối B01'), ('D07_TOAN', 'Toán Khối D07'), ('D07_HOA', 'Hóa Học Khối D07'), ('D07_TA', 'Tiếng Anh Khối D07'), ('B02_TOAN', 'Toán Khối B02'), ('B02_SINH', 'Sinh Học Khối B02'), ('B02_DIA', 'Địa Lý Khối B02'), ('C01_VAN', 'Ngữ Văn Khối C01'), ('C01_TOAN', 'Toán Khối C01'), ('C01_LY', 'Vật Lý Khối C01'), ('D14_VAN', 'Ngữ Văn Khối D14'), ('D14_LS', 'Lịch Sử Khối D14'), ('D14_TA', 'Tiếng Anh Khối D14'), ('D15_VAN', 'Ngữ Văn Khối D15'), ('D15_DIA', 'Địa Lý Khối D15'), ('D15_TA', 'Tiếng Anh Khối D15')], max_length=10, unique=True),
        ),
    ]
