# Generated by Django 5.1.6 on 2025-10-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblock', '0006_alter_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('public', 'Công lập'), ('private', 'Tư thục')], max_length=50)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('block', models.CharField(choices=[('A', 'Khối A'), ('A1', 'Khối A1'), ('B', 'Khối B'), ('C', 'Khối C'), ('D', 'Khối D'), ('OTHER', 'Khối khác')], max_length=10)),
                ('subject_1', models.CharField(max_length=50)),
                ('subject_2', models.CharField(max_length=50)),
                ('subject_3', models.CharField(max_length=50)),
                ('benchmark_2024', models.FloatField()),
                ('admission_quota', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='testblock.university')),
            ],
        ),
    ]
