# Generated by Django 5.1.6 on 2025-04-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="content",
            field=models.CharField(default="tuyen sinh", max_length=1000000),
        ),
    ]
