# Generated by Django 5.1.6 on 2025-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0002_school_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="description",
            field=models.CharField(
                default="Là một trong những cơ sở giáo dục hàng đầu tại Việt Nam, chuyên cung cấp chương trình đào tạo chất lượng cao, gắn liền với thực tiễn và hội nhập quốc tế. Với sứ mệnh đào tạo nguồn nhân lực có trình độ chuyên môn vững vàng, tư duy sáng tạo và đạo đức nghề nghiệp, trường luôn không ngừng đổi mới trong công tác giảng dạy, nghiên cứu khoa học và chuyển giao công nghệ. Trường hiện có nhiều khoa chuyên ngành đa dạng như Công nghệ thông tin, Kinh tế, Ngoại ngữ, Kỹ thuật, và Quản trị kinh doanh, đáp ứng nhu cầu phát triển của xã hội hiện đại. Cơ sở vật chất khang trang, đội ngũ giảng viên giàu kinh nghiệm cùng môi trường học tập thân thiện, năng động là những yếu tố giúp sinh viên phát triển toàn diện về kiến thức, kỹ năng và nhân cách.",
                max_length=1000000,
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="email",
            field=models.CharField(default="tuyensinh@hcmute.edu.vn", max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="establishyear",
            field=models.CharField(default=2000, max_length=10),
        ),
        migrations.AddField(
            model_name="school",
            name="numberOfMajor",
            field=models.CharField(default="50", max_length=10),
        ),
        migrations.AddField(
            model_name="school",
            name="phoneNumber",
            field=models.CharField(default="028.3722.5724", max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="scale",
            field=models.CharField(default="36000+", max_length=10),
        ),
    ]
