# Generated by Django 5.1.6 on 2025-04-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "school",
            "0003_school_description_school_email_school_establishyear_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="establishyear",
            field=models.IntegerField(default=2000, max_length=10),
        ),
        migrations.AlterField(
            model_name="school",
            name="numberOfMajor",
            field=models.IntegerField(default=50, max_length=10),
        ),
    ]
