# Generated by Django 5.1.6 on 2025-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0004_alter_school_establishyear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="establishyear",
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name="school",
            name="numberOfMajor",
            field=models.IntegerField(default=50),
        ),
    ]
