# Generated by Django 5.1.6 on 2025-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_alter_school_establishyear_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="content",
            field=models.CharField(default="tuyen sinh", max_length=1000000, null=True),
        ),
    ]
