# Generated by Django 5.1.6 on 2025-04-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0006_alter_school_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="content",
            field=models.TextField(default="tuyen sinh", max_length=1000000, null=True),
        ),
    ]
