# Generated by Django 5.1.6 on 2025-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0008_alter_school_description_alter_school_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="image",
            field=models.ImageField(
                null=True, upload_to="static/assets/img/news/", verbose_name="Hình ảnh"
            ),
        ),
    ]
