# Generated by Django 5.1.6 on 2025-05-27 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0009_school_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_id", models.CharField(max_length=10)),
                ("major_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolMajor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point", models.FloatField()),
                ("admission_targets", models.IntegerField()),
                (
                    "major",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.major"
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="school.school"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="major",
            name="schools",
            field=models.ManyToManyField(
                through="school.SchoolMajor", to="school.school"
            ),
        ),
    ]
