# Generated by Django 5.1.6 on 2025-05-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0010_major_schoolmajor_major_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmajor",
            name="admission_targets",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="schoolmajor",
            name="point",
            field=models.FloatField(null=True),
        ),
    ]
