# Generated by Django 5.1.6 on 2025-05-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0011_alter_schoolmajor_admission_targets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="major_id",
            field=models.CharField(max_length=10, verbose_name="Mã ngành"),
        ),
        migrations.AlterField(
            model_name="major",
            name="major_name",
            field=models.CharField(max_length=100, verbose_name="Tên ngành"),
        ),
        migrations.AlterField(
            model_name="schoolmajor",
            name="admission_targets",
            field=models.IntegerField(null=True, verbose_name="Chỉ tiêu"),
        ),
        migrations.AlterField(
            model_name="schoolmajor",
            name="point",
            field=models.FloatField(null=True, verbose_name="Điểm chuẩn"),
        ),
    ]
