# Generated by Django 5.1.6 on 2025-05-27 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0012_alter_major_major_id_alter_major_major_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="major",
            name="major_id",
        ),
    ]
