# Generated by Django 5.1.6 on 2025-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0013_remove_major_major_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="email",
            field=models.CharField(
                default="tuyensinh@edu.vn", max_length=50, null=True
            ),
        ),
    ]
