# Generated by Django 5.1.6 on 2025-05-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0014_alter_school_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="school",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="static/assets/img/schools/",
                verbose_name="Hình ảnh",
            ),
        ),
    ]
