# Generated by Django 5.1.6 on 2025-10-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0015_alter_school_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="admissions_year",
            field=models.PositiveSmallIntegerField(
                default=2023, max_length=4, null=True
            ),
        ),
    ]
