# Generated by Django 5.1.6 on 2025-10-21 06:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0016_school_admissions_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="admissions_year",
        ),
    ]
