# Generated by Django 5.1.6 on 2025-10-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0017_remove_school_admissions_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmajor",
            name="admission_year",
            field=models.PositiveSmallIntegerField(default=2023, max_length=4),
        ),
    ]
