# Generated by Django 5.1.6 on 2025-10-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0018_schoolmajor_admission_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmajor",
            name="admission_combination",
            field=models.CharField(
                default="A00, A01, D01",
                max_length=100,
                null=True,
                verbose_name="Tổ hợp xét tuyển",
            ),
        ),
        migrations.AlterField(
            model_name="schoolmajor",
            name="admission_year",
            field=models.PositiveSmallIntegerField(
                default=2023, max_length=4, null=True, verbose_name="Năm tuyển sinh"
            ),
        ),
    ]
