# Generated by Django 5.1.6 on 2025-10-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0019_schoolmajor_admission_combination_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="major_name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Tên ngành"
            ),
        ),
    ]
