# Generated by Django 5.1.6 on 2025-10-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0020_alter_major_major_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolmajor",
            name="is_high_quality",
            field=models.BooleanField(
                default=False, verbose_name="Chương trình chất lượng cao"
            ),
        ),
    ]
