# Generated by Django 5.1.6 on 2025-10-21 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0021_schoolmajor_is_high_quality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schoolmajor",
            name="admission_year",
            field=models.PositiveSmallIntegerField(
                default=2023,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2023),
                    django.core.validators.MaxValueValidator(2025),
                ],
                verbose_name="Năm tuyển sinh",
            ),
        ),
    ]
