# Generated by Django 5.2.7 on 2025-12-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_alter_schoolmajor_admission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(default='www.iuh.edu.vn', max_length=100, null=True),
        ),
    ]
