# Generated by Django 5.1.6 on 2025-04-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000000)),
                ("answer1", models.CharField(max_length=20)),
                ("answer2", models.CharField(max_length=20)),
                ("answer3", models.CharField(max_length=20)),
                ("answer4", models.CharField(max_length=20)),
            ],
        ),
    ]
