# Generated by Django 5.1.6 on 2025-04-19 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="question",
            new_name="content",
        ),
    ]
