# Generated by Django 5.1.6 on 2025-10-06 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='B', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='C', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='D', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='num_questions',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.major'),
        ),
    ]
