# Generated by Django 5.1.6 on 2025-10-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_choice_options_alter_major_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
