# Generated by Django 5.1.6 on 2025-05-19 21:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expert_name",
                    models.CharField(max_length=50, verbose_name="Tên chuyên gia"),
                ),
                (
                    "expert_image",
                    models.ImageField(
                        upload_to="static/assets/img/experts", verbose_name="Hình ảnh"
                    ),
                ),
                (
                    "expert_description",
                    models.CharField(max_length=200, null=True, verbose_name="Mô tả"),
                ),
                (
                    "expert_work_day",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Ngày vào làm"
                    ),
                ),
            ],
        ),
    ]
