# Generated by Django 5.1.6 on 2025-05-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expert",
            name="expert_name",
        ),
        migrations.AddField(
            model_name="expert",
            name="expert_first_name",
            field=models.CharField(
                default="Chuyên viên", max_length=50, verbose_name="Họ đệm"
            ),
        ),
        migrations.AddField(
            model_name="expert",
            name="expert_last_name",
            field=models.CharField(
                default="Chuyên viên", max_length=50, verbose_name="Tên"
            ),
        ),
    ]
