# Generated by Django 5.1.6 on 2025-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "homepage",
            "0002_remove_expert_expert_name_expert_expert_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="expert_first_name",
            field=models.CharField(max_length=50, verbose_name="Họ đệm"),
        ),
        migrations.AlterField(
            model_name="expert",
            name="expert_last_name",
            field=models.CharField(max_length=50, verbose_name="Tên"),
        ),
    ]
