# Generated by Django 5.1.6 on 2025-09-18 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0004_alter_expert_options_alter_expert_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expert",
            options={},
        ),
        migrations.AlterModelTable(
            name="expert",
            table="Experts",
        ),
    ]
