# Generated by Django 5.1.6 on 2025-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0005_alter_expert_options_alter_expert_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="expert_description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Mô tả"
            ),
        ),
        migrations.AlterField(
            model_name="expert",
            name="expert_image",
            field=models.ImageField(
                blank=True,
                upload_to="static/assets/img/experts",
                verbose_name="Hình ảnh",
            ),
        ),
    ]
