# Generated by Django 5.1.6 on 2025-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0006_alter_expert_expert_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expert",
            old_name="expert_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="expert_first_name",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="expert_image",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="expert_last_name",
        ),
        migrations.RemoveField(
            model_name="expert",
            name="expert_work_day",
        ),
        migrations.AddField(
            model_name="expert",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="static/assets/img/experts"),
        ),
        migrations.AddField(
            model_name="expert",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expert",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Nam"), ("Female", "Nữ"), ("Other", "Khác")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expert",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
