# Generated by Django 5.1.6 on 2025-09-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0007_rename_expert_description_expert_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="phone_number",
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
