# Generated by Django 5.1.6 on 2025-10-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homepage", "0008_alter_expert_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
