# Generated by Django 5.1.6 on 2025-10-09 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên trường')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã trường')),
                ('location', models.CharField(max_length=100, verbose_name='Địa điểm')),
                ('type', models.CharField(choices=[('public', 'Công lập'), ('private', 'Tư thục')], max_length=50, verbose_name='Loại hình')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Trường đại học',
                'verbose_name_plural': 'Các trường đại học',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên ngành')),
                ('code', models.CharField(max_length=20, verbose_name='Mã ngành')),
                ('block', models.CharField(choices=[('A', 'Khối A'), ('A1', 'Khối A1'), ('B', 'Khối B'), ('C', 'Khối C'), ('D', 'Khối D'), ('OTHER', 'Khối khác')], max_length=10, verbose_name='Khối thi')),
                ('subject_1', models.CharField(max_length=50, verbose_name='Môn 1')),
                ('subject_2', models.CharField(max_length=50, verbose_name='Môn 2')),
                ('subject_3', models.CharField(max_length=50, verbose_name='Môn 3')),
                ('benchmark_2024', models.FloatField(verbose_name='Điểm chuẩn 2024')),
                ('admission_quota', models.IntegerField(verbose_name='Chỉ tiêu')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='admission_predictor.university', verbose_name='Trường đại học')),
            ],
            options={
                'verbose_name': 'Ngành học',
                'verbose_name_plural': 'Các ngành học',
                'unique_together': {('code', 'university')},
            },
        ),
    ]
