# Generated by Django 5.1.6 on 2025-10-09 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission_predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên mô hình')),
                ('version', models.CharField(max_length=20, verbose_name='Phiên bản')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Độ chính xác')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Mô hình dự đoán',
                'verbose_name_plural': 'Các mô hình dự đoán',
            },
        ),
        migrations.AddField(
            model_name='major',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả ngành'),
        ),
        migrations.AlterField(
            model_name='major',
            name='block',
            field=models.CharField(choices=[('A00', 'Khối A00 (Toán, Lý, Hóa)'), ('A01', 'Khối A01 (Toán, Lý, Anh)'), ('B00', 'Khối B00 (Toán, Hóa, Sinh)'), ('C00', 'Khối C00 (Văn, Sử, Địa)'), ('D01', 'Khối D01 (Toán, Văn, Anh)'), ('D07', 'Khối D07 (Toán, Hóa, Anh)'), ('OTHER', 'Khối khác')], max_length=10, verbose_name='Khối thi'),
        ),
        migrations.AlterField(
            model_name='major',
            name='subject_1',
            field=models.CharField(choices=[('Toán', 'Toán'), ('Lý', 'Vật lý'), ('Hóa', 'Hóa học'), ('Sinh', 'Sinh học'), ('Văn', 'Ngữ văn'), ('Sử', 'Lịch sử'), ('Địa', 'Địa lý'), ('Anh', 'Tiếng Anh'), ('Trung', 'Tiếng Trung'), ('Pháp', 'Tiếng Pháp'), ('Nga', 'Tiếng Nga'), ('Nhật', 'Tiếng Nhật'), ('Đức', 'Tiếng Đức'), ('Hàn', 'Tiếng Hàn')], max_length=50, verbose_name='Môn 1'),
        ),
        migrations.AlterField(
            model_name='major',
            name='subject_2',
            field=models.CharField(choices=[('Toán', 'Toán'), ('Lý', 'Vật lý'), ('Hóa', 'Hóa học'), ('Sinh', 'Sinh học'), ('Văn', 'Ngữ văn'), ('Sử', 'Lịch sử'), ('Địa', 'Địa lý'), ('Anh', 'Tiếng Anh'), ('Trung', 'Tiếng Trung'), ('Pháp', 'Tiếng Pháp'), ('Nga', 'Tiếng Nga'), ('Nhật', 'Tiếng Nhật'), ('Đức', 'Tiếng Đức'), ('Hàn', 'Tiếng Hàn')], max_length=50, verbose_name='Môn 2'),
        ),
        migrations.AlterField(
            model_name='major',
            name='subject_3',
            field=models.CharField(choices=[('Toán', 'Toán'), ('Lý', 'Vật lý'), ('Hóa', 'Hóa học'), ('Sinh', 'Sinh học'), ('Văn', 'Ngữ văn'), ('Sử', 'Lịch sử'), ('Địa', 'Địa lý'), ('Anh', 'Tiếng Anh'), ('Trung', 'Tiếng Trung'), ('Pháp', 'Tiếng Pháp'), ('Nga', 'Tiếng Nga'), ('Nhật', 'Tiếng Nhật'), ('Đức', 'Tiếng Đức'), ('Hàn', 'Tiếng Hàn')], max_length=50, verbose_name='Môn 3'),
        ),
        migrations.CreateModel(
            name='AdmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Năm tuyển sinh')),
                ('benchmark', models.FloatField(verbose_name='Điểm chuẩn')),
                ('admission_quota', models.IntegerField(verbose_name='Chỉ tiêu')),
                ('actual_admitted', models.IntegerField(blank=True, null=True, verbose_name='Số lượng trúng tuyển thực tế')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_data', to='admission_predictor.major', verbose_name='Ngành học')),
            ],
            options={
                'verbose_name': 'Dữ liệu tuyển sinh',
                'verbose_name_plural': 'Dữ liệu tuyển sinh',
                'unique_together': {('major', 'year')},
            },
        ),
    ]
